
services:
  # === MariaDB for Product Service ===
  product-db:
    image: mariadb:10.5
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: product_db
    ports:
      - "3307:3306"
    volumes:
      - product_data:/var/lib/mysql

  product-service:
    build: ./product-service
    depends_on:
      - product-db
    ports:
      - "3001:3001"
    restart: unless-stopped

  # === MariaDB for Order Service ===
  order-db:
    image: mariadb:10.5
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: order_db
    ports:
      - "3308:3306"
    volumes:
      - order_data:/var/lib/mysql

  order-service:
    build: ./order-service
    depends_on:
      - order-db
    ports:
      - "3002:3002"
    restart: unless-stopped

  # === MariaDB for Customer Service ===
  customer-db:
    image: mariadb:10.5
    container_name: customer-db
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: customer_db
    ports:
      - "3309:3306"
    volumes:
      - customer_data:/var/lib/mysql

  customer-service:
    build: ./customer-service
    depends_on:
      - customer-db
    ports:
      - "3003:3003"
    restart: unless-stopped
 # === MariaDB for Payment Service ===
  payment-db:
    image: mariadb:10.5
    container_name: payment-db
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: payment_db
    ports:
      - "3310:3306"
    volumes:
      - payment_data:/var/lib/mysql

  payment-service:
    build: ./payment-service
    depends_on:
      - payment-db
    ports:
      - "3004:3004"
    restart: unless-stopped
  # === API Gateway ===
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
      - customer-service
      - payment-service
    restart: unless-stopped

volumes:
  product_data:
  order_data:
  customer_data:
  payment_data: